-- MARKS
INSERT INTO MARK (MARK_ID, MARK_NAME) VALUES (1, 'Renault');
INSERT INTO MARK (MARK_ID, MARK_NAME) VALUES (2, 'Peugeot');
INSERT INTO MARK (MARK_ID, MARK_NAME) VALUES (3, 'Fiat');
INSERT INTO MARK (MARK_ID, MARK_NAME) VALUES (4, 'Nissan');
INSERT INTO MARK (MARK_ID, MARK_NAME) VALUES (5, 'Citroen');


-- MODELS
INSERT INTO MODEL (MODEL_ID, MODEL_NAME, MODEL_MARK_ID) VALUES (1, 'Clio', 1);
INSERT INTO MODEL (MODEL_ID, MODEL_NAME, MODEL_MARK_ID) VALUES (2, '307', 2);
INSERT INTO MODEL (MODEL_ID, MODEL_NAME, MODEL_MARK_ID) VALUES (3, 'Ducato', 3);
INSERT INTO MODEL (MODEL_ID, MODEL_NAME, MODEL_MARK_ID) VALUES (4, 'Scudo', 3);


-- CARS
INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL_ID, CAR_YEAR, CAR_COLOR, CAR_IMMATRICULATION) VALUES (1, 'Clio 4', 1, '2008', 'Red', 'aa-123-aa');
INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL_ID, CAR_YEAR, CAR_COLOR, CAR_IMMATRICULATION) VALUES (2, '307', 2, '2009', 'Black', 'bb-234-bb');
INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL_ID, CAR_YEAR, CAR_COLOR, CAR_IMMATRICULATION) VALUES (3, 'ducato', 3, '2009', 'White', 'cc-256-cc');
INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL_ID, CAR_YEAR, CAR_COLOR, CAR_IMMATRICULATION) VALUES (4, 'scudo', 4, '2004', 'Blue', 'dd-456-dd');