CREATE TABLE BRAND (
    BRAND_ID         INTEGER     NOT NULL,
    BRAND_UUID       VARCHAR(36) NOT NULL,
    BRAND_NAME       VARCHAR(40),
    CONSTRAINT BRAND_ID_PK PRIMARY KEY (BRAND_ID)
);


CREATE TABLE MODEL (
    MODEL_ID        INTEGER      NOT NULL,
    MODEL_UUID      VARCHAR(36)  NOT NULL,
    MODEL_NAME      VARCHAR(40),
    MODEL_BRAND_ID   INTEGER,
    CONSTRAINT MODEL_ID_PK PRIMARY KEY (MODEL_ID),
    CONSTRAINT MODEL_BRAND_ID_FK FOREIGN KEY (MODEL_BRAND_ID) REFERENCES BRAND(BRAND_ID)
);


CREATE TABLE CAR (
    CAR_ID                  INTEGER      NOT NULL AUTO_INCREMENT,
    CAR_UUID                VARCHAR(36)  NOT NULL,
    CAR_NAME                VARCHAR(40),
    CAR_MODEL_ID            INTEGER,
    CAR_YEAR                VARCHAR(4),
    CAR_COLOR               VARCHAR(10),
    CAR_IMMATRICULATION     VARCHAR(10),
    CONSTRAINT CAR_ID_PK PRIMARY KEY (CAR_ID),
    CONSTRAINT CAR_MODEL_ID_FK FOREIGN KEY (CAR_MODEL_ID) REFERENCES MODEL(MODEL_ID)
);


