CREATE TABLE MARK (
    MARK_ID         INTEGER     NOT NULL,
    MARK_NAME       VARCHAR(40),
    CONSTRAINT MARK_ID_PK PRIMARY KEY (MARK_ID)
);


CREATE TABLE MODEL (
    MODEL_ID        INTEGER      NOT NULL,
    MODEL_NAME      VARCHAR(40),
    MODEL_MARK_ID   INTEGER,
    CONSTRAINT MODEL_ID_PK PRIMARY KEY (MODEL_ID),
    CONSTRAINT MODEL_MARK_ID_FK FOREIGN KEY (MODEL_MARK_ID) REFERENCES MARK(MARK_ID)
);


CREATE TABLE CAR (
    CAR_ID                  INTEGER      NOT NULL AUTO_INCREMENT,
    CAR_NAME                VARCHAR(40),
    CAR_MODEL_ID            INTEGER,
    CAR_YEAR                VARCHAR(4),
    CAR_COLOR               VARCHAR(10),
    CAR_IMMATRICULATION     VARCHAR(10),
    CONSTRAINT CAR_ID_PK PRIMARY KEY (CAR_ID),
    CONSTRAINT CAR_MODEL_ID_FK FOREIGN KEY (CAR_MODEL_ID) REFERENCES MODEL(MODEL_ID)
);


