CREATE TABLE BRAND (
    BRAND_ID         INTEGER     NOT NULL,
    BRAND_UUID       VARCHAR(36) NOT NULL,
    BRAND_NAME       VARCHAR(40) NOT NULL,
    CONSTRAINT BRAND_ID_PK PRIMARY KEY (BRAND_ID)
);

CREATE TABLE CAR (
    CAR_ID                  INTEGER      NOT NULL,
    CAR_UUID                VARCHAR(36)  NOT NULL,
    CAR_NAME                VARCHAR(40),
    CAR_BRAND_ID            INTEGER      NOT NULL,
    CAR_YEAR                VARCHAR(4),
    CAR_COLOR               VARCHAR(10),
    CAR_IMMATRICULATION     VARCHAR(10),
    CONSTRAINT CAR_ID_PK PRIMARY KEY (CAR_ID),
    CONSTRAINT CAR_BRAND_ID_FK FOREIGN KEY (CAR_BRAND_ID) REFERENCES BRAND(BRAND_ID)
);