FROM my-alpine-builder

ARG jarName
ARG port
ARG version

ENV jarName=${jarName}
ENV port=${port}
ENV version=${version}

ADD ${jarName}/target/${jarName}-${version}-SNAPSHOT-exec.jar ${jarName}.${version}.jar
ADD ${jarName}/wait-for-discovery.sh wait-for-discovery.sh

RUN chmod 755 wait-for-discovery.sh

EXPOSE ${port}