version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  cars:
    image: cars
    container_name: cars
    ports:
      - 8090:8090
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  clients:
    image: clients
    container_name: clients
    ports:
      - 8091:8091
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  locations:
    image: locations
    container_name: locations
    ports:
      - 8092:8092
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092