version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
    depends_on:
      - zookeeper

  discovery-server:
    image: saadelbannani/discovery-server:1.0.0
    container_name: discovery-server
    build:
      context: .
      dockerfile: Dockerfile-Servers
      args:
        jarName: discovery-server
        port: 9091
        version: 1.0.0
    ports:
      - 9091:9091

  api-gateway:
    image: saadelbannani/api-gateway:1.0.0
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile-Services
      args:
        jarName: api-gateway
        port: 9090
        version: 1.0.0
    entrypoint: /wait-for-discovery.sh
    ports:
      - 9090:9090
    depends_on:
      - discovery-server
    links:
      - discovery-server:discovery-server
      - cars:cars
      - clients:clients
      - locations:locations

  clients:
    image: saadelbannani/clients:1.1.1
    container_name: clients
    build:
      context: .
      dockerfile: Dockerfile-Services
      args:
        jarName: clients
        port: 8091
        version: 1.1.1
    entrypoint: /wait-for-discovery.sh
    ports:
      - 8091:8091
    depends_on:
      - discovery-server
    links:
      - discovery-server:discovery-server

  cars:
    image: saadelbannani/cars:1.1.1
    container_name: cars
    build:
      context: .
      dockerfile: Dockerfile-Services
      args:
        jarName: cars
        port: 8090
        version: 1.1.1
    entrypoint: /wait-for-discovery.sh
    ports:
      - 8090:8090
    depends_on:
      - zookeeper
      - kafka
      - discovery-server
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    links:
      - discovery-server:discovery-server

  locations:
    image: saadelbannani/locations:1.1.1
    container_name: locations
    build:
      context: .
      dockerfile: Dockerfile-Services
      args:
        jarName: locations
        port: 8092
        version: 1.1.1
    entrypoint: /wait-for-discovery.sh
    ports:
      - 8092:8092
    depends_on:
      - kafka
      - zookeeper
      - discovery-server
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    links:
      - discovery-server:discovery-server