-- SEQUENCES
CREATE SEQUENCE PHONE_SEQ INCREMENT BY 1;
CREATE SEQUENCE ADDRESS_SEQ INCREMENT BY 1;
CREATE SEQUENCE CLIENT_SEQ INCREMENT BY 1;

-- TABLES
CREATE TABLE PHONE (
    PHONE_ID             NUMBER     NOT NULL,
    PHONE_UUID           VARCHAR2(36)  NOT NULL,
    PHONE_PREFIX         VARCHAR2(4),
    PHONE_NUMBER         VARCHAR2(20),
    CONSTRAINT PHONE_ID_PK PRIMARY KEY (PHONE_ID)
);

CREATE TABLE ADDRESS (
    ADDRESS_ID          NUMBER      NOT NULL,
    ADDRESS_UUID        VARCHAR2(36)  NOT NULL,
    ADDRESS_NUMBER      VARCHAR2(5),
    ADDRESS_LINE        VARCHAR2(40),
    ADDRESS_ZIP_CODE    VARCHAR2(5),
    ADDRESS_CITY        VARCHAR2(40),
    ADDRESS_COUNTRY     VARCHAR2(40),
    CONSTRAINT ADDRESS_ID_PK PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE CLIENT (
    CLIENT_ID               NUMBER      NOT NULL,
    CLIENT_UUID             VARCHAR2(36)  NOT NULL,
    CLIENT_FNAME            VARCHAR2(40),
    CLIENT_LNAME            VARCHAR2(40),
    CLIENT_DATE_BIRTH       TIMESTAMP,
    CLIENT_ADDRESS_ID       NUMBER,
    CLIENT_PHONE_ID         NUMBER,
    CONSTRAINT CLIENT_ID_PK PRIMARY KEY (CLIENT_ID),
    CONSTRAINT CLIENT_ADDRESS_ID_FK FOREIGN KEY (CLIENT_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    CONSTRAINT CLIENT_PHONE_ID_FK FOREIGN KEY (CLIENT_PHONE_ID) REFERENCES PHONE(PHONE_ID)
);