-- LOCATION
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NUMBER, LOCATION_CLIENT_ID, LOCATION_CAR_ID) VALUES (1, '1', 1, 1);
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NUMBER, LOCATION_CLIENT_ID, LOCATION_CAR_ID) VALUES (2, '2', 2, 2);
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NUMBER, LOCATION_CLIENT_ID, LOCATION_CAR_ID) VALUES (3, '3', 3, 3);

-- FACTURE
INSERT INTO FACTURE (FACTURE_ID, FACTURE_NUMBER, FACTURE_TYPE, FACTURE_STAT, FACTURE_PRICE, FACTURE_START_DATE, FACTURE_END_DATE, FACTURE_LOCATION_ID)
    VALUES (1, '1', 'Courte location', 'En cours', 500, '2018-08-01', '2018-08-30', 1);
INSERT INTO FACTURE (FACTURE_ID, FACTURE_NUMBER, FACTURE_TYPE, FACTURE_STAT, FACTURE_PRICE, FACTURE_START_DATE, FACTURE_END_DATE, FACTURE_LOCATION_ID)
    VALUES (2, '3', 'Courte location', 'Fini', 250, '2018-08-01', '2018-08-10', 2);
INSERT INTO FACTURE (FACTURE_ID, FACTURE_NUMBER, FACTURE_TYPE, FACTURE_STAT, FACTURE_PRICE, FACTURE_START_DATE, FACTURE_END_DATE, FACTURE_LOCATION_ID)
    VALUES (3, '3', 'Courte location', 'En cours', 1500, '2018-08-01', '2018-10-30', 3);

