CREATE TABLE LOCATION (
    LOCATION_ID             INTEGER     NOT NULL,
    LOCATION_NUMBER         VARCHAR(40),
    LOCATION_CLIENT_ID      INTEGER,
    LOCATION_CAR_ID         INTEGER,

    CONSTRAINT LOCATION_ID_PK PRIMARY KEY (LOCATION_ID),
    CONSTRAINT LOCATION_CLIENT_ID_FK FOREIGN KEY (LOCATION_CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
    CONSTRAINT LOCATION_CAR_ID_FK FOREIGN KEY (LOCATION_CAR_ID) REFERENCES CAR(CAR_ID)
);

CREATE TABLE FACTURE (
    FACTURE_ID             INTEGER     NOT NULL,
    FACTURE_NUMBER         VARCHAR(40),
    FACTURE_TYPE           VARCHAR(40),
    FACTURE_STAT           VARCHAR(40),
    FACTURE_PRICE          INTEGER,
    FACTURE_START_DATE     TIMESTAMP,
    FACTURE_END_DATE       TIMESTAMP,
    FACTURE_LOCATION_ID    INTEGER,

    CONSTRAINT FACTURE_ID_PK PRIMARY KEY (FACTURE_ID),
    CONSTRAINT FACTURE_LOCATION_ID_FK FOREIGN KEY (FACTURE_LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);