-- SEQUENCES
CREATE SEQUENCE LOCATION_SEQ INCREMENT BY 10;
CREATE SEQUENCE FACTURE_SEQ INCREMENT BY 10;

-- TABLES
CREATE TABLE FACTURE (
    FACTURE_ID             INTEGER     NOT NULL,
    FACTURE_UUID           VARCHAR(36) NOT NULL,
    FACTURE_NUMBER         VARCHAR(40),
    FACTURE_TYPE           VARCHAR(40),
    FACTURE_STAT           VARCHAR(40),
    FACTURE_PRICE          INTEGER,
    FACTURE_START_DATE     TIMESTAMP,
    FACTURE_END_DATE       TIMESTAMP,
    FACTURE_LOCATION_ID    INTEGER,

    CONSTRAINT FACTURE_ID_PK PRIMARY KEY (FACTURE_ID)
);

CREATE TABLE LOCATION (
    LOCATION_ID             INTEGER     NOT NULL,
    LOCATION_UUID           VARCHAR(36) NOT NULL,
    LOCATION_NUMBER         VARCHAR(40),
    LOCATION_CLIENT_UUID    VARCHAR(36) NOT NULL,
    LOCATION_CAR_UUID       VARCHAR(36) NOT NULL,
    LOCATION_FACTURE_ID     INTEGER,

    CONSTRAINT LOCATION_ID_PK PRIMARY KEY (LOCATION_ID),
    CONSTRAINT LOCATION_FACTURE_ID_FK FOREIGN KEY (LOCATION_FACTURE_ID) REFERENCES FACTURE(FACTURE_ID)
);

ALTER TABLE FACTURE ADD CONSTRAINT FACTURE_LOCATION_ID_FK FOREIGN KEY (FACTURE_LOCATION_ID)
REFERENCES LOCATION(LOCATION_ID);