-- SEQUENCES
CREATE SEQUENCE LOCATION_SEQ INCREMENT BY 10;
CREATE SEQUENCE FACTURE_SEQ INCREMENT BY 10;

-- TABLES
CREATE TABLE FACTURE (
    FACTURE_ID             NUMBER     NOT NULL,
    FACTURE_UUID           VARCHAR2(36) NOT NULL,
    FACTURE_NUMBER         VARCHAR2(40),
    FACTURE_TYPE           VARCHAR2(40),
    FACTURE_STAT           VARCHAR2(40),
    FACTURE_PRICE          NUMBER,
    FACTURE_START_DATE     TIMESTAMP,
    FACTURE_END_DATE       TIMESTAMP,
    FACTURE_LOCATION_ID    NUMBER,

    CONSTRAINT FACTURE_ID_PK PRIMARY KEY (FACTURE_ID)
);

CREATE TABLE LOCATION (
    LOCATION_ID             NUMBER     NOT NULL,
    LOCATION_UUID           VARCHAR2(36) NOT NULL,
    LOCATION_NUMBER         VARCHAR2(40),
    LOCATION_CLIENT_UUID    VARCHAR2(36) NOT NULL,
    LOCATION_CAR_UUID       VARCHAR2(36) NOT NULL,
    LOCATION_FACTURE_ID     NUMBER,

    CONSTRAINT LOCATION_ID_PK PRIMARY KEY (LOCATION_ID),
    CONSTRAINT LOCATION_FACTURE_ID_FK FOREIGN KEY (LOCATION_FACTURE_ID) REFERENCES FACTURE(FACTURE_ID)
);

ALTER TABLE FACTURE ADD CONSTRAINT FACTURE_LOCATION_ID_FK FOREIGN KEY (FACTURE_LOCATION_ID)
REFERENCES LOCATION(LOCATION_ID);