-- SEQUENCES
CREATE SEQUENCE BRAND_SEQ INCREMENT BY 10;
CREATE SEQUENCE CAR_SEQ INCREMENT BY 10;

-- TABLES
CREATE TABLE BRAND (
    BRAND_ID         NUMBER     NOT NULL,
    BRAND_UUID       VARCHAR2(36) NOT NULL,
    BRAND_NAME       VARCHAR2(40) NOT NULL,
    CONSTRAINT BRAND_ID_PK PRIMARY KEY (BRAND_ID)
);

CREATE TABLE CAR (
    CAR_ID                  NUMBER      NOT NULL,
    CAR_UUID                VARCHAR2(36)  NOT NULL,
    CAR_NAME                VARCHAR2(40),
    CAR_BRAND_ID            NUMBER      NOT NULL,
    CAR_YEAR                VARCHAR2(4),
    CAR_COLOR               VARCHAR2(10),
    CAR_IMMATRICULATION     VARCHAR2(10),
    CAR_DISPONIBILITY       NUMBER(1,0)   NOT NULL,

    CONSTRAINT CAR_ID_PK PRIMARY KEY (CAR_ID),
    CONSTRAINT CAR_BRAND_ID_FK FOREIGN KEY (CAR_BRAND_ID) REFERENCES BRAND(BRAND_ID)
);